### Importing Numpy

In [1]:
import numpy as np

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
a = np.array([1, 2, 3], dtype=np.uint8)
print(a)
print(a.dtype)


b = np.array([1, 2, 3], dtype=complex)
print(b)
print(b.dtype)


[1 2 3]
uint8
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [7]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [9]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# np.random
np.random.random((3,4))

array([[0.86353619, 0.12689833, 0.91726664, 0.73510793],
       [0.01272881, 0.25805306, 0.95658856, 0.80227786],
       [0.4081538 , 0.72205208, 0.66678943, 0.01067083]])

In [12]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [13]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [14]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# ndim
a3.ndim

3

In [16]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
# itemsize
a3.itemsize

8

In [19]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [20]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [23]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [25]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[94., 55., 45.],
       [99., 36., 12.],
       [48., 61., 40.]])

In [26]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([446688., 120780.,  21600.])

In [27]:
# mean/median/std/var
np.var(a1,axis=1)

array([ 446.88888889, 1346.        ,   74.88888889])

In [28]:
# trigonomoetric functions
np.sin(a1)

array([[-0.24525199, -0.99975517,  0.85090352],
       [-0.99920683, -0.99177885, -0.53657292],
       [-0.76825466, -0.96611777,  0.74511316]])

In [29]:
# Angle array in degrees
angles_deg = np.array([0, 30, 45, 60, 90])
# Convert to radians
angles_rad = np.deg2rad(angles_deg)

print("Angles in degrees:", angles_deg)
print("Angles in radians:", angles_rad)

print("Sine:", np.sin(angles_rad))
print("Cosine:", np.cos(angles_rad))
print("Tangent:", np.tan(angles_rad))

Angles in degrees: [ 0 30 45 60 90]
Angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [30]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [31]:
a1

array([[94., 55., 45.],
       [99., 36., 12.],
       [48., 61., 40.]])

In [32]:
# log and exponents
np.exp(a1)   #e**a1  e=2.718

array([[6.66317622e+40, 7.69478527e+23, 3.49342711e+19],
       [9.88903032e+42, 4.31123155e+15, 1.62754791e+05],
       [7.01673591e+20, 3.10429794e+26, 2.35385267e+17]])

In [33]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[100.,  42.,  21.],
       [ 74.,  77.,  73.]])

### Indexing and Slicing

In [34]:


a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [35]:
a1

array([[94., 55., 45.],
       [99., 36., 12.],
       [48., 61., 40.]])

In [36]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a2[1,0]

np.int64(4)

In [38]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [39]:
a3[1,0]

np.int64(15)

In [40]:
a3[1,1]

np.int64(16)

In [41]:
a1

array([[94., 55., 45.],
       [99., 36., 12.],
       [48., 61., 40.]])

In [42]:
a1[2:5:2]

array([[48., 61., 40.]])

In [43]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [44]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [45]:
a2[1,::3]

array([4, 7])

In [46]:
a2[0,:]

array([0, 1, 2, 3])

In [47]:
a2[:,2]

array([ 2,  6, 10])

In [48]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [49]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [51]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [52]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [53]:
a1

for i in a1:
  print(i)

[94. 55. 45.]
[99. 36. 12.]
[48. 61. 40.]


In [54]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [56]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [58]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [59]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [60]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])